# Generated by Django 4.0.2 on 2022-03-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custacc',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='custposreg',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='custprofile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='custtype',
            options={'managed': False},
        ),
    ]
