# Generated by Django 4.0.2 on 2022-03-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custtype',
            options={},
        ),
    ]
