# Generated by Django 4.0.2 on 2022-03-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_custtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='custposdeclar',
            name='pos_declar_ques',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.custposdeclarques'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custposdeclar',
            name='pos_reg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.custposreg'),
            preserve_default=False,
        ),
    ]
