# Generated by Django 4.0.2 on 2022-03-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'postcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
    ]
