# Generated by Django 4.0.2 on 2022-03-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'managed': False},
        ),
    ]
